- name: Config server
  template: 
    src: templates/server.conf.j2 
    dest: /etc/openvpn/server.conf

- name: Ensure /etc/openvpn/auth/ directory is exists
  file: 
    path: /etc/openvpn/auth/ 
    state: directory    

- name: Config LDAP authentication    
  template:
    src: templates/auth-ldap.conf.j2
    dest: /etc/openvpn/auth/auth-ldap.conf

- name: Enable and Start OpenVPN
  command: "{{ item }}"
  with_items: 
  - systemctl enable openvpn@server
#  - systemctl restart openvpn@server
  
- name: Read CA file
  slurp:
    src: /etc/openvpn/ca.pem
  register: ca_cert

- name: Read client key file
  slurp:
    src: /etc/openvpn/client-key.pem
  register: client_key

- name: Read client certificate file
  slurp:
    src: /etc/openvpn/client-cert.pem
  register: client_cert

- name: Create client configure
  template:
    src: templates/client.vpn.j2
    dest: /etc/openvpn/client.vpn
